### ISSUE TITLE
Accept a filter as input

### ISSUE THREAD

**Issue by danielo515** [danielo515/TIddlywiki5-EncryptTiddlerPlugin#2]
Widget should accept a filter as its input, and then encrypt or decrypt all the tiddlers that match that filter.

**Comment by reflectionalist** [comment]
**@danielo515**:

Is this intended to handle my request for batch encryption?

**Comment by danielo515** [comment]
Hello @reflectionalist ,

Yes it is. After this I can create a ui to manage batch encryptions. Take a look at #3
