### ISSUE TITLE
Provide a control pannel

### ISSUE THREAD

**Issue by danielo515** [danielo515/TIddlywiki5-EncryptTiddlerPlugin#3]
When #2 gets implemented, users will need a place to easily manage encrypt/unencrypt tasks.
Since they can build this themselves I think is better if the plugin includes some kind of control panel with  most common operations like:
- [x] Batch encryption based on a filter
- [x] Batch unencrypt based on a filter
- [ ] List of encrypted tiddlers.

**Comment by danielo515** [comment]
I'm not sure how this should look like.

Currently I have two fields, one per password with two ugly buttons, one for encrypt and other for decrypt, and a second text field to write the filter you want to use. Any idea to improve it is welcome. Here is a small screenshot:

 
![image](https://cloud.githubusercontent.com/assets/2270425/6963307/d8d91aae-d93d-11e4-804b-fdad13db585b.png)

**Comment by Jermolene** [comment]
@danielo515 I have to say that I think what you've got is pretty good.

It would be helpful if the tiddler listing indicated whether each tiddler was encrypted or not?

One possibility might be to add a button for bulk encryption to the search results in the filter tab of $:/AdvancedSearch, just like we do for export.

**Comment by twMat** [comment]
Nice working!!

When you say:
 
>Currently I have two fields, one per password with two ugly buttons, one for encrypt and other for decrypt, and a second text field to write the filter you want to use.

...you mean "Currently I have two fields, one **for the** password with two [...]" - right? (I'm not nitpicking, I'm trying to make sure I understand).

Assuming you mean "for the", then I'm thinking:

Why are the buttons both showing at the same time? It will only make sense to do one of them, no? So maybe there could be some sensing mechanism to detect if the filter result is already encrypted (and then show button Decrypt) and vice versa. Or maybe this would not work with your solution.

(...and I guess a very polished version would either have the button/s grayed out, or even not showing at all, before there are any results to actually apply it to. Probably not worth spending time on.)

Does the layout reflect the workflow? Unless I misunderstand, one must first enter the filter and thereafter decide Encrypt/Decrypt. If so, I suggest putting the filter box above the buttons. Now, this would separate it from the filter result list - so maybe the password stuff could be to the right of the filter stuff. Like:

![encrypt](https://cloud.githubusercontent.com/assets/4534056/6963797/6db8c516-d943-11e4-93d3-a57eaecff408.png)

**Comment by twMat** [comment]
>It would be helpful if the tiddler listing indicated whether each tiddler was encrypted or not?

+1

**Comment by danielo515** [comment]
Hello @jermolene

> @danielo515 I have to say that I think what you've got is pretty good.

Thank you  very much

> It would be helpful if the tiddler listing indicated whether each tiddler was encrypted or not?

Yes. I though about that. I think the better approach is to use a listItemTemplate. Thank you for remind me that, I forgot about that idea already!

**Comment by danielo515** [comment]
Hello @twMat

> ...you mean "Currently I have two fields, one for the password with two [...]" - right? (I'm not nitpicking, I'm trying to make sure I understand).

Yes, that is exactly what I mean. Thank you

>Why are the buttons both showing at the same time? It will only make sense to do one of them, no? So maybe there could be some sensing mechanism to detect if the filter result is already encrypted (and then show button Decrypt) and vice versa. Or maybe this would not work with your solution.

The problem is that there is nothing that forces the results to be all encrypted or non encrypted. So it makes sense to have both buttons at the same time.

>Unless I misunderstand, one must first enter the filter and thereafter decide Encrypt/Decrypt. If so, I suggest putting the filter box above the buttons. 

That's correct, I like the idea but I don't like to have so many items in the same "row". I think you gave me a new idea:
Instead of displaying the input text for the password, just display both buttons (probably as icons) and when you cilck on one of them a drop-down to input the password appears.

**Comment by danielo515** [comment]
Hello @twMat , @Jermolene 

Taking with your suggestions in mind I created a second version. Now there is a lock icon and when you click it a popup that is opened. I'm not sure about where to place the popup, next to the lock button or below the search field. 

Here are a couple of screenshots, please let me know what do you thing about it

**Unexpanded**

![unexpanded](https://cloud.githubusercontent.com/assets/2270425/6985116/04e17860-da30-11e4-9955-489a34ab8356.PNG)


**Popup next to button**
![expanded_right](https://cloud.githubusercontent.com/assets/2270425/6985107/e58a13aa-da2f-11e4-9539-4652b17930f1.PNG)

**Popup BELOW**
![image](https://cloud.githubusercontent.com/assets/2270425/6985099/c4018632-da2f-11e4-99b0-c79fb363875b.png)

I would also want to have the opinion of @felixhayashi

**Comment by felixhayashi** [comment]
> I would also want to have the opinion of @felixhayashi

:bowtie:

The popup idea is nice. If you use it, I would put it "below-left" of the unlock symbol 

![c4018632-da2f-11e4-99b0-c79fb363875b](https://cloud.githubusercontent.com/assets/4307137/6987537/56e60e4c-da48-11e4-8284-97574cf7c13c.png)

On the other hand, I think it is an essential part of the form and should be initially visible (as https://github.com/danielo515/TIddlywiki5-EncryptTiddlerPlugin/issues/3#issuecomment-88872735).

So tough decision ;)

-Felix

**Comment by twMat** [comment]
Hm. Having played around a bit with it in my own draging program I come to the conclusion that your first suggestion is probably best *but* putting the password + buttons row under the filter field.

It captures the workflow except that the filter result list is separated - but it is positioned so close that there should not be any confusion.

I'm not very fond of a popup here because I simply don't see a reason for it visually. If you insist on one, then I suggest to remove the visible frame+shading.

This also omits the need for a lock icon. I also note that it is not obvious if such an icon-lock should be opened or closed. Both/neither make sense here given that you have both Encrypt and Decrypt. Plus, the tiddler itself has this icon but there it symbolizes a status rather than an action.

(BTW, this makes me realize the X symbol also has double meaning in TW; close or make-empty. This is used elsewhere in TW though, so you should probably stick with it.)

You have decided to be generous to the user and write "Search via a filter expression", providing a link to what I assume is an explanation. If this is justified (and it probably is) then maybe a link to how one should actually Encrypt/Decrypt. As indicated in my initial post, it is a bit confusing with both commands available at the same time. For *this* it would be suitable with a popup (with frame+shading) as it is peripheral information and not the main feature. Could be a button with a questionmark or such. 

Ok, just my opinions.

**Comment by Jermolene** [comment]
> BTW, this makes me realize the X symbol also has double meaning in TW; close or make-empty

The plan was to consistently use "X" for close and the trashcan icon for destroy/make-empty, we should fix any inconsistencies.

**Comment by danielo515** [comment]
Hello @twMat 

I think that your ideas really makes sense. I leaved the idea of using a popup because, as you said, is a non-sense here. Also the password an encrypt/decrypt controls only appears when there is some filter written. 

Here you can see the latest "implementation"

![image](https://cloud.githubusercontent.com/assets/2270425/6992228/19165cf0-dac2-11e4-8f43-571980568ab1.png)


I also included @Jermolene suggestion to indicate if each tiddler is encrypted or not. This is indicated with the presence of a small padlock.
